---

- name: Install iptables
  apt:
    name: iptables
    state: present

- name: Disable Ubuntu UFW
  import_tasks: disable_ufw.yaml
  when:
    - ansible_os_family == "Debian"


- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Allow established connections on INPUT chain 
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow access from trusted network 
  iptables:
    chain: INPUT
    source: "{{ item }}"
    jump: ACCEPT
  with_items: "{{ iptables_trusted_networks }}"

- name: Allow SSH access from network
  iptables:
    chain: INPUT
    source: "{{ item }}"
    destination_port: 22
    protocol: tcp
    jump: ACCEPT
  with_items: "{{ iptables_ssh_networks }}"

- name: Allow access for public service/port
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    protocol: tcp
    jump: ACCEPT
  with_items: "{{ iptables_public_ports }}"

- name: Set policy for INPUT chain
  iptables:
    chain: INPUT
    policy: DROP

- name: Set policy for FORWARD chain
  iptables:
    chain: FORWARD
    policy: DROP

- name: Set policy for OUTPUT chain
  iptables:
    chain: OUTPUT
    policy: ACCEPT
